# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test Django
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        DEPLOYMENTKEY: ${{ secrets.DEPLOYMENTKEY }}
    - name: Create identity file
      run: |
        echo "$DEPLOYMENTKEY" | base64 --decode > deployment.key
        chmod 400 deployment.key
    - name: Update server
      run: |
        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i deployment.key bitnami@63.33.13.4 sudo /home/bitnami/website/update.sh
