# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        DEPLOYMENTKEY: ${{ secrets.DEPLOYMENTKEY }}
    - name: Create identity file
      run: |
        echo "$DEPLOYMENTKEY" | base64 --decode > deployment.key
        chmod 400 deployment.key
    - name: Update server
      run: |
        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i deployment.key bitnami@63.33.13.4
